description: This environment controls what items should be shown on the Shotgun Tank
  menu for shots.
engines:
  tk-shotgun:
    apps:
      tk-shotgun-folders:
        deny_permissions: []
        deny_platforms: []
        location: {name: tk-shotgun-folders, type: app_store, version: v0.1.5}
      tk-shotgun-launchfolder:
        deny_permissions: []
        deny_platforms: []
        location: {name: tk-shotgun-launchfolder, type: app_store, version: v0.1.5}
      tk-shotgun-launchhiero: '@launch_hiero'
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
      tk-shotgun-launchscreeningroom: '@launch_shotgun_screeningroom'
    debug_logging: false
    location: {name: tk-shotgun, type: app_store, version: v0.3.3}
frameworks: null
include: ./includes/app_launchers.yml
