description: This environment controls what items should be shown on the Shotgun Tank
  menu for publishes.
engines:
  tk-shotgun:
    apps:
      tk-shotgun-launchmaya: '@launch_maya'
      tk-shotgun-launchnuke: '@launch_nuke'
      tk-shotgun-launchphotoshop: '@launch_photoshop'
      tk-shotgun-launchpublish:
        deny_permissions: []
        deny_platforms: []
        hook_launch_publish: default
        location: {name: tk-shotgun-launchpublish, type: app_store, version: v0.1.14}
        viewer_extensions: [exr, dpx, cin]
        viewer_path_linux: '@rv_linux'
        viewer_path_mac: '@rv_mac'
        viewer_path_windows: '@rv_win'
    debug_logging: false
    location: {name: tk-shotgun, type: app_store, version: v0.3.4}
frameworks: null
includes: [./includes/app_launchers.yml, ./includes/paths.yml]
